# Generated by Django 5.0.1 on 2024-01-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_image',
        ),
    ]
