# Generated by Django 5.0.1 on 2024-01-25 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField(max_length=500)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.service')),
            ],
        ),
    ]
