# Generated by Django 5.0.1 on 2024-01-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_servicedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='image',
            new_name='service_image',
        ),
    ]
