# Generated by Django 5.0.1 on 2024-02-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_image_service_service_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='service_image',
            new_name='image',
        ),
    ]
